CREATE TABLE forms(
  id         int GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  form_id    uuid NOT NULL,
  name       text,
  created_at timestamp NOT NULL,
  data       json NOT NULL
);

CREATE TAble layouts(
  id         int GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  layout_id  text NOT NULL,
  name       text,
  created_at timestamp NOT NULL,
  data       jsonb NOT NULL
);
